### ISSUE TITLE
how to fix this problem?

### ISSUE THREAD

**Issue by psyvirgin** [beakerbrowser/dathttpd#28]
$ dathttpd
Serving from /home/qyqx/.dathttpd
Proxying proxy.local http://localhost:8080
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
Handling ACME challenges and serving https 443
Unhandled rejection Error: listen EADDRINUSE :::80
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at /usr/local/lib/node_modules/dathttpd/node_modules/greenlock-express/lex.js:40:82
    at Promise._execute (/usr/local/lib/node_modules/dathttpd/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/dathttpd/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/dathttpd/node_modules/bluebird/js/release/promise.js:79:10)
    at /usr/local/lib/node_modules/dathttpd/node_modules/greenlock-express/lex.js:39:21
    at Array.forEach (<anonymous>)
    at Object.opts.listen (/usr/local/lib/node_modules/dathttpd/node_modules/greenlock-express/lex.js:38:16)
    at Multidat (/usr/local/lib/node_modules/dathttpd/lib/server.js:104:10)
    at /usr/local/lib/node_modules/dathttpd/node_modules/multidat/index.js:29:5
    at /usr/local/lib/node_modules/dathttpd/node_modules/multidrive/index.js:52:7
    at f (/usr/local/lib/node_modules/dathttpd/node_modules/map-limit/node_modules/once/once.js:17:25)

Serving datprotocol.dat.local dat://2727ede22ea034798f81e5e774987e39b0658c8904bff26b4b35601e5372dfe0
Serving dat.local dat://2727ede22ea034798f81e5e774987e39b0658c8904bff26b4b35601e5372dfe0

how to fix it

**Comment by pfrazee** [comment]
Hey @psyvirgin. You're using the example config, which isn't going to work very well in general.

The error is `Unhandled rejection Error: listen EADDRINUSE :::80`. That means you already have a server running at port 80.
